#ifndef __GLOBALS_H
#define __GLOBALS_H

#define RE_CHAR_TYPE_PARENS 0
#define RE_CHAR_TYPE_CHAR 1
#define RE_CHAR_TYPE_BRACKETS 2

enum a_re_quantifiers{A_CHAR, A_STAR, A_ESCAPE, A_PLUS, A_BRACES, A_DOLLAR, A_CIR_FLEX, A_QUESTION, A_NESTED, A_RANGE};
enum a_errors{A_NO_ERR, A_INVALID_RE, A_MEM_ERR};
enum a_cc_words{A_CC_ALNUM = 1, A_CC_ALPHA, A_CC_BLANK, A_CC_CNTRL, A_CC_DIGIT, A_CC_GRAPH, A_CC_LOWER, A_CC_PRINT, A_CC_PUCNT, A_CC_SPACE, A_CC_UPPER, A_CC_XDIGIT, A_CC_ERR = 0};

#endif
